#!/usr/bin/env python3
"""
Schema for build-time enrichment output.

The organising rule: every derived claim is traceable to the message or
document it came from. `evidence` is not optional metadata — it is what
separates "Lucy knows Doris holds the med kit" from "Lucy made that up",
and it is what lets a wrong inference be found and corrected later.
"""
import sqlite3

# A claim can cite a chat message, a camp document, or a roster row. The roster
# is the odd one out and deliberately so: it is not prose someone wrote, it is
# the signup sheets normalised into one row per person, so it is primary data
# rather than a derived claim. `camp_member.record` is its text, and a quote
# citing it is a verbatim substring of that, exactly as for the other two.
SOURCE_TABLES = ("person_content", "camp_knowledge", "camp_member")

# Claim tables whose rows must each be backed by at least one evidence row.
# person_profile is keyed by person_id, not by a synthetic id — see CLAIM_TABLES
# handling below.
CLAIM_TABLES = ("entity", "entity_fact", "person_profile", "expertise",
                "relationship", "lore", "camp_fact", "personality")

# Claim tables keyed by person_id rather than a synthetic id.
PERSON_KEYED = ("person_profile", "personality")

_ENTITY_KINDS = ("vehicle", "structure", "tool", "place", "tradition", "asset")
_FACT_CATEGORIES = ("access", "contents", "location", "handling", "history")
_EXPERTISE_STRENGTHS = ("strong", "moderate", "mentioned")
_CAMP_FACT_CATEGORIES = ("how", "where", "who", "when", "rule")


def _in_list(values: tuple) -> str:
    return ", ".join(f"'{v}'" for v in values)


SCHEMA = f"""
-- A named thing the camp talks about that no document defines.
CREATE TABLE IF NOT EXISTS entity (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL UNIQUE,
    kind          TEXT NOT NULL CHECK (kind IN ({_in_list(_ENTITY_KINDS)})),
    summary       TEXT NOT NULL,
    first_seen    TEXT,
    last_seen     TEXT,
    mention_count INTEGER DEFAULT 0
);

-- `source` says where an alias came from. NULL means it was found in the
-- corpus by the discovery pass (or added by hand); 'ask_vocab' means it was
-- generated by enrich_ask_vocab.py (mishearings, spelling variants). The
-- distinction is what lets that stage wipe and rewrite only its own rows on
-- a re-run without ever touching an alias somebody actually observed.
CREATE TABLE IF NOT EXISTS entity_alias (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    alias     TEXT NOT NULL,
    source    TEXT,
    UNIQUE (entity_id, alias)
);

-- One fact per row, dated. Two rows may contradict each other on purpose:
-- the corpus contains real disagreements and resolving them silently would
-- be inventing an answer the camp never reached.
CREATE TABLE IF NOT EXISTS entity_fact (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id   INTEGER NOT NULL REFERENCES entity(id) ON DELETE CASCADE,
    fact        TEXT NOT NULL,
    category    TEXT CHECK (category IS NULL OR category IN ({_in_list(_FACT_CATEGORIES)})),
    asserted_on TEXT
);

CREATE TABLE IF NOT EXISTS person_profile (
    person_id    INTEGER PRIMARY KEY REFERENCES person(id) ON DELETE CASCADE,
    summary      TEXT NOT NULL,
    years_active TEXT,
    chapter      TEXT,
    known_for    TEXT
);

CREATE TABLE IF NOT EXISTS expertise (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    person_id INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
    topic     TEXT NOT NULL,
    strength  TEXT NOT NULL CHECK (strength IN ({_in_list(_EXPERTISE_STRENGTHS)})),
    UNIQUE (person_id, topic)
);

CREATE TABLE IF NOT EXISTS relationship (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    person_a INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
    person_b INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
    kind     TEXT NOT NULL,               -- builds_with | chapter | co_shift | mentors
    strength INTEGER DEFAULT 1,
    UNIQUE (person_a, person_b, kind)
);

CREATE TABLE IF NOT EXISTS lore (
    id     INTEGER PRIMARY KEY AUTOINCREMENT,
    title  TEXT NOT NULL,
    story  TEXT NOT NULL,
    year   INTEGER,
    people TEXT                           -- comma-separated names, for display only
);

-- The names a camper is actually called, as against the one the corpus wrote
-- down.
--
-- entity_alias has done this for THINGS since enrich_ask_vocab.py existed --
-- 321 rows of mishearings, spellings and colloquial names, which is why
-- "Oz Hole" and "OzHole" both resolve. People had nothing, and people are what
-- questions are mostly about. Measured on the owner's phone: of 105 distinct
-- spoken questions, 16 arrived mistranscribed, and the cluster was names.
--
-- The variants were already in the database and were being deleted.
-- dedupe_people.py groups by normalised name, keeps the row with the most
-- messages and DROPs the rest -- so "CeCe", "CeCe Garlan" and "Cece" all
-- vanished into "Cece Garland", and "Saami", "Saami " and an email address
-- vanished into "Saami Khoury". Every one of those is a way somebody
-- refers to that person. They are recorded here before the merge instead.
--
-- `source` says where an alias came from, because they are not equally
-- trustworthy: `merged` is a spelling the corpus itself used, `part` is a
-- first or last name split off a full one, and `generated` is a model's guess
-- at a mishearing. A consumer that wants only observed names can filter.
CREATE TABLE IF NOT EXISTS person_alias (
    person_id INTEGER NOT NULL,
    alias     TEXT    NOT NULL,
    source    TEXT    NOT NULL,          -- merged | part | generated
    PRIMARY KEY (person_id, alias),
    FOREIGN KEY (person_id) REFERENCES person(id)
);

-- E7. One vector per claim, for the questions that share no words with their
-- answer -- "how do we get water delivered" against a row about picking up
-- service vouchers. Written by embed_claims.py, which owns the encoding
-- convention; read on the phone by Embedder.swift, which must use the same
-- task prefix or the two sides quietly disagree.
--
-- Not a foreign key, and deliberately so: claim_table names which table
-- claim_id points into, and SQLite cannot express that. embed_claims.py
-- rebuilds the whole table rather than patching it, so a stale row cannot
-- outlive the claim it described.
--
-- The BLOB is little-endian Float32, 768 of them, read directly by Swift.
CREATE TABLE IF NOT EXISTS claim_embedding (
    claim_table TEXT    NOT NULL,         -- camp_fact | entity_fact | lore
    claim_id    INTEGER NOT NULL,
    embedding   BLOB    NOT NULL,
    model_name  TEXT    NOT NULL,
    PRIMARY KEY (claim_table, claim_id)
);

-- Documents are not entities — their facts don't belong in entity_fact.
-- One fact per row, extracted from a camp_knowledge document. `year` is the
-- document's own year (not inferred), so a 2019 rule can be told from a
-- 2025 one without cross-referencing evidence.
CREATE TABLE IF NOT EXISTS camp_fact (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    topic    TEXT NOT NULL,     -- water, power, kitchen, shifts, bikes, shade, waste, arrival, safety...
    fact     TEXT NOT NULL,
    category TEXT CHECK (category IS NULL OR category IN ({_in_list(_CAMP_FACT_CATEGORIES)})),
    year     INTEGER
);

-- The words a camper would use to ASK for a claim when the claim's own text
-- doesn't contain them — "medkit" for a fact that only says "first aid".
-- Written by enrich_ask_vocab.py; today claim_table is always 'camp_fact'.
--
-- Deliberately NOT a claim table, so no evidence row backs it: an ask word
-- asserts nothing about the world. It can only route a question to a claim
-- whose own evidence stands, and on-device ranking scores it below a direct
-- text match, so a bad generated word costs a candidate row, never a wrong
-- top answer.
--
-- No CHECK on claim_table on purpose: a CHECK freezes at CREATE TABLE time
-- and widening it later needs the same migration dance `evidence` already
-- requires (see _evidence_check_is_stale). These rows are wiped and rewritten
-- wholesale by their own stage, so the constraint would not earn that cost.
CREATE TABLE IF NOT EXISTS ask_word (
    claim_table TEXT NOT NULL,
    claim_id    INTEGER NOT NULL,
    word        TEXT NOT NULL,       -- lowercased single word or short phrase
    UNIQUE (claim_table, claim_id, word)
);

-- How someone comes across in the camp's own chat, as opposed to what they
-- do (that is person_profile).
--
-- Deliberately not a psychological assessment. These are real people in a
-- small community who will read each other's entries, and a chat log supports
-- "writes long enthusiastic messages about food logistics and volunteers for
-- the 6am shift" far better than it supports a claim about someone's
-- character.
-- So: their voice, what they reliably care about, how they show up when there
-- is work to do — each backed by messages they actually wrote.
CREATE TABLE IF NOT EXISTS personality (
    person_id  INTEGER PRIMARY KEY REFERENCES person(id),
    summary    TEXT NOT NULL,     -- two or three sentences, warm and specific
    voice      TEXT,              -- how they write: brisk, wry, all-caps, emoji
    cares_about TEXT,             -- what they return to unprompted
    shows_up_as TEXT,             -- what they are like to camp alongside
    signature_quote TEXT          -- one line of theirs that sounds like them
);

-- Who has camped with us, from the signup sheets in `PS People/`. One row per
-- person, not per person-per-year: `years_attended` is the list they said yes
-- to. `record` is the row rendered as text, and is what evidence quotes cite.
--
-- email and phone are held here because the sheets have them and matching
-- people across years depends on them. They are dropped on the way to the
-- device — a phone in a pocket at a festival is not where 150 people's contact
-- details belong.
CREATE TABLE IF NOT EXISTS camp_member (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    name           TEXT NOT NULL,
    first_name     TEXT,
    last_name      TEXT,
    nickname       TEXT,
    email          TEXT,
    phone          TEXT,
    home_city      TEXT,
    years_attended TEXT,               -- '2019,2022,2023' — years they said yes
    years_listed   TEXT,               -- every year they appear on a sheet
    year_count     INTEGER,
    first_year     INTEGER,
    last_year      INTEGER,
    statuses       TEXT,               -- '2019=attending;2022=maybe'
    match_notes    TEXT,               -- how records were merged, or why not
    record         TEXT NOT NULL,      -- the row as prose; evidence quotes it
    -- The same human in the chat corpus, where they appear under whatever
    -- WhatsApp had for them — "Oz", "Piotr", "Nick Darnell". NULL when no
    -- unambiguous match exists, which is most of the corpus: 1,035 names in
    -- chat against 313 on the roster, and neither side is a subset.
    person_id      INTEGER REFERENCES person(id),
    person_match   TEXT,               -- how the link was made, for auditing
    -- Every chat row judged to be this same human, comma-separated, including
    -- person_id. WhatsApp exported Katharine Hensley as both "Kat Hensley" (106
    -- messages) and "Katharine Hensley" (110), and linking to one left the
    -- other standing in the People list as a second person.
    person_ids     TEXT
);

-- The spine. claim_table/claim_id name the derived row; source_table/source_id
-- name the corpus row it came from; quote is the exact supporting text.
CREATE TABLE IF NOT EXISTS evidence (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    claim_table  TEXT NOT NULL CHECK (claim_table IN ({_in_list(CLAIM_TABLES)})),
    claim_id     INTEGER NOT NULL,
    source_table TEXT NOT NULL CHECK (source_table IN ({_in_list(SOURCE_TABLES)})),
    source_id    INTEGER NOT NULL,
    quote        TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evidence_claim  ON evidence(claim_table, claim_id);
CREATE INDEX IF NOT EXISTS idx_evidence_source ON evidence(source_table, source_id);
CREATE INDEX IF NOT EXISTS idx_fact_entity     ON entity_fact(entity_id);
CREATE INDEX IF NOT EXISTS idx_expertise_topic ON expertise(topic);
CREATE INDEX IF NOT EXISTS idx_camp_fact_topic ON camp_fact(topic);
-- Lookup is by word (a query term arriving from the phone); the reverse
-- direction, claim -> words, is covered by the UNIQUE index's prefix.
CREATE INDEX IF NOT EXISTS idx_ask_word_word   ON ask_word(word);
"""

# SQLite cannot express a foreign key whose target table varies by row, so the
# referential check for `evidence.source_id` is enforced by trigger instead.
TRIGGERS = """
CREATE TRIGGER IF NOT EXISTS evidence_source_exists
BEFORE INSERT ON evidence
BEGIN
    SELECT RAISE(ABORT, 'evidence.source_id does not exist in the named source table')
    WHERE (NEW.source_table = 'person_content'
           AND NOT EXISTS (SELECT 1 FROM person_content WHERE id = NEW.source_id))
       OR (NEW.source_table = 'camp_knowledge'
           AND NOT EXISTS (SELECT 1 FROM camp_knowledge WHERE id = NEW.source_id))
       OR (NEW.source_table = 'camp_member'
           AND NOT EXISTS (SELECT 1 FROM camp_member WHERE id = NEW.source_id));
END;
"""


def _evidence_check_is_stale(conn: sqlite3.Connection) -> bool:
    """evidence's CHECK constraints are fixed at CREATE TABLE time, so
    `CREATE TABLE IF NOT EXISTS` is a no-op against a database created
    before a new claim table (e.g. camp_fact) or source table (camp_member)
    existed. Detect that case by checking the live table's stored SQL, not by
    trusting this module's own idea of the lists.

    Both lists are checked. Only claim_table was, and adding camp_member to
    SOURCE_TABLES then left every existing database rejecting roster evidence
    with a CHECK failure that named the right column and gave no hint why."""
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='evidence'"
    ).fetchone()
    if row is None or row[0] is None:
        return False
    existing_sql = row[0]
    return not all(f"'{t}'" in existing_sql
                   for t in CLAIM_TABLES + SOURCE_TABLES)


def _migrate_evidence_table(conn: sqlite3.Connection) -> None:
    """Recreate `evidence` with the current CHECK, preserving every existing
    row. DROP TABLE also drops the table's indexes and its
    evidence_source_exists trigger; the caller recreates both immediately
    after via SCHEMA/TRIGGERS, so this leaves nothing dangling."""
    rows = conn.execute(
        "SELECT id, claim_table, claim_id, source_table, source_id, quote "
        "FROM evidence").fetchall()
    conn.execute("DROP TABLE evidence")
    conn.executescript(SCHEMA)
    conn.executescript(TRIGGERS)
    conn.executemany(
        "INSERT INTO evidence (id, claim_table, claim_id, source_table, "
        "source_id, quote) VALUES (?,?,?,?,?,?)", rows)


# Columns added to a table after it first shipped. `CREATE TABLE IF NOT EXISTS`
# is a no-op against a database that already has the table, so a new column is
# silently absent until it is added by hand — the same trap as the evidence
# CHECK constraints above, and it fails just as unhelpfully ("no such column").
_ADDED_COLUMNS = {
    "camp_member": {
        "person_id": "INTEGER REFERENCES person(id)",
        "person_match": "TEXT",
        "person_ids": "TEXT",
    },
    # NULL on every pre-existing row, which is exactly what NULL means here:
    # not generated (see the entity_alias comment in SCHEMA).
    "entity_alias": {
        "source": "TEXT",
    },
}


def _add_missing_columns(conn: sqlite3.Connection) -> None:
    for table, columns in _ADDED_COLUMNS.items():
        existing = {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}
        if not existing:
            continue                      # table not created yet; SCHEMA will
        for name, decl in columns.items():
            if name not in existing:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")


def create_enrichment_tables(conn: sqlite3.Connection) -> None:
    conn.execute("PRAGMA foreign_keys = ON")
    if _evidence_check_is_stale(conn):
        _migrate_evidence_table(conn)
    conn.executescript(SCHEMA)
    conn.executescript(TRIGGERS)
    _add_missing_columns(conn)
    conn.commit()


def drop_enrichment_tables(conn: sqlite3.Connection) -> None:
    """Enrichment is fully re-derivable; dropping is how a re-run starts clean.

    `camp_member` is deliberately not dropped — it is a source table, like
    `camp_knowledge`, not a derived claim. But the roster *facts* built from it
    live in `camp_fact` and do go, and nothing notices: `camp_member` is not a
    claim table, so `verify_evidence_complete` still passes with 313 member
    rows and no facts referring to them. Re-run `build_people.py --install`
    after any enrichment reset or the roster silently stops answering.
    """
    for t in ("evidence", "lore", "relationship", "expertise",
              "person_profile", "personality", "entity_fact", "entity_alias",
              "entity", "camp_fact", "ask_word"):
        conn.execute(f"DROP TABLE IF EXISTS {t}")
    conn.commit()


def find_unevidenced_claims(conn) -> dict[str, list[int]]:
    """Claim rows with no evidence row pointing at them, keyed by table.

    Evidence completeness cannot be enforced at insert time — a claim must exist
    before evidence can reference its id. Every pipeline pass calls this before
    it commits, so an unevidenced claim fails the run that produced it rather
    than surfacing later as an answer with nothing behind it.
    """
    offenders: dict[str, list[int]] = {}
    for table in CLAIM_TABLES:
        id_col = "person_id" if table in PERSON_KEYED else "id"
        rows = conn.execute(f"""
            SELECT t.{id_col}
            FROM {table} t
            WHERE NOT EXISTS (
                SELECT 1 FROM evidence e
                WHERE e.claim_table = ? AND e.claim_id = t.{id_col}
            )
            ORDER BY t.{id_col}
        """, (table,)).fetchall()
        if rows:
            offenders[table] = [r[0] for r in rows]
    return offenders


def verify_evidence_complete(conn) -> None:
    """Raise if any claim row lacks evidence. Call at the end of every pass."""
    offenders = find_unevidenced_claims(conn)
    if not offenders:
        return
    parts = []
    for table, ids in offenders.items():
        preview = ", ".join(str(i) for i in ids[:5])
        more = f", ... ({len(ids)} total)" if len(ids) > 5 else ""
        parts.append(f"{table}: {len(ids)} row(s) without evidence (ids: {preview}{more})")
    raise ValueError("Unevidenced claims found — " + "; ".join(parts))
